<?php
  include_once('_inc/classes/Menu.php');
  include_once('_inc/classes/Assets.php');
  require_once('_inc/classes/Database.php');
  include_once('_inc/classes/Contact.php');
  include_once('_inc/classes/Review.php');
  include_once('_inc/classes/User.php');
  include_once('_inc/classes/Authenticate.php');
?>